sprueche = [
    "Wie viele Microsoft-Programmierer braucht man, um eine Glühbirne zu wechseln? Keine. Microsoft erklärt einfach die Dunkelheit zum Standard.",
    "Das Wort Windows stammt aus einem alten Dialekt der Apachen und bedeuted: 'Weißer Mann starren durch Glasscheibe auf Sanduhr'.",
    "Was ist der Unterschied zwischen 'Jurassic Park' und Microsoft? Bei dem einen macht ein verrückter Geschäftsmann ein Vermögen mit Biestern die schon längst ausgestorben sein sollten, und das andere ist ein Film von Steven Spielberg.",
    "Wie viele Windows-Anwender braucht man um eine Glühbirne zu wechseln? 100! Einer wechselt die Birne, 99 klicken die Fehlermeldungen weg.",
    "Linux wird nie das meistinstallierte Betriebssystem sein, wenn man bedenkt, wie oft man Windows neu installieren muss!",
    "Chuck Norris kann STRG + ALT + ENTF gleichzeitig mit einem Finger drücken.",
    "Woran erkennt man einen extrovertierten Informatiker? Er schaut beim Reden auf DEINE Schuhe.",
    "Wer im Netz Anstand und Respekt verliert, der ist auch im realen Leben für nichts zu gebrauchen!",
    "Nach über 30 Jahren Computertechnik müssten die Tastaturhersteller eigentlich gelernt haben, dass Tastaturen unten Abflusslöcher für den Kaffee brauchen. [Peter Becker dt. Informatiker, geb. 1949]",
    "Die letzten Worte eines Informatikers 'Ich bleibe hier bis das Problem gelöst ist.'",
    "Wenn jemand mit einem der gängigen sogenannten Textverarbeitungsprogramme (aka Schreibmaschinenemulatoren auf Crack) ein Textdokument zusammenstümpert, ist das oft eine sehr eindrucksvolle Demonstration, warum es 'Trial & Error' heißt und nicht 'Trial & Success'.",
    "Erst wenn der letzte FTP Server kostenpflichtig, der letzte GNU-Sourcecode verkauft, der letzte Algorithmus patentiert, der letzte Netzknoten kommerzialisert ist, werdet Ihr merken, dass Manager nicht programmieren können.",
    "Die Funktionsweise eines Computers heißt genau dann wohldefiniert, wenn man sein Verhalten in mindestens einem Paralleluniversum als deterministisch bezeichnen würde. [C. Endres]",
    "UNIX IST benutzerfreundlich ... es ist nur etwas wählerisch ...",
    "UNIX ist simpel. Es erfordert lediglich Genialität um seine Einfachheit zu verstehen.",
    "WWW steht für World Wide Wait",
    "Windows ist nicht 'nur' eine grafische Benutzeroberfläche, sondern eines der erfolgreichsten Spiele der letzten Jahre' [Aus einem PC-Seminar]",
    "'Künstliche Intelligenz' ('KI') hat genausoviel mit Intelligenz zu tun wie 'Naturidentische Aromastoffe' ('BRRH') mit natürlichem Geschmack. [Murphy]",
    "Soziologen sind nützlich, aber keiner will sie. Bei einem Informatiker ist es umgekehrt.",
    "Bildung lässt sich nicht downloaden. [Günter Jauch]",
    "(Dawkins ist der Meinung, man solle) ... komplizierten Rechenmaschinen (= Computer) Selbstbewusstsein zusprechen. So wie man beim Leben sagt: stellt das richtige Eiweiß her, dann krabbelt es auch, so kann man hier sagen: baut den richtigen Computer, dann sagt sie auch 'Mama' und 'Papa' und bekommt das Wahlrecht, wenn sie 18 ist. [Reinhard Löw, 1983]",
    "Fragen Sie nicht, was Ihr Computer für Sie tun kann. Fragen Sie, was Sie für Ihren Computer tun können.",
    "Schizophrenie ist auch nur eine Form von Multitasking …",
    "Der Anwender steht immer im Mittelpunkt – und da steht er jedem im Weg. [Entwicklerweisheit]",
    "Diese Software verdient die 3 großen GGG: Gesehen — Gelacht — Gelöscht",
    "Es ist bemerkenswert, daß nur vielleicht 10% aller Programmierer Programme ohne Verwendung von Flussdiagrammen erfolgreich schreiben können. Unglücklicherweise glauben aber 90%, daß sie der Gruppe dieser 10% angehören. [Rodnay Zaks]",
    "Irren ist menschlich. Aber für das richtige Chaos, braucht man einen Computer.",
    "Was macht ein Pirat am Computer? Er drückt die Enter-Taste.",
    "Hardware nennt man die Teile eines Computers die man treten kann - Jeff Pesis",
    "Der Computer rechnet mit allem, nur nicht mit seinem Besitzer. [Dieter Hildebrandt]",
    "Programmieren erklärt: den Code durchgehen und mit der linken Hand offene und mit der rechten geschlossene Klammern zählen!",
    "Ich schiebe so was immer auf 'Java'. Irgendwelche Feindbilder muss man nach dem Fall der Berliner Mauer schließlich haben.",
    "SAP = 'Sanduhr-Anzeige-Programm'; 'Sammelstelle Arbeitsloser Physiker'",
    "IBM = 'Immer besser Manuell'"
]